#=============================================#
#                 v.1.2.8                     #  
# █▀▀▀█ █  █ █  █ ▄▀▀▄ ▀█▀ █     █▀▄▀█ █▀▀▄   #
# ▀▀▀▄▄ █   █▀▀█ █▄▄█  █  █     █ █ █ █  █   #
# █▄▄▄█ ▀▄▄▀ █  █ █  █ ▄█▄ █▄▄█  █   █ █▄▄▀   #
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧        #
#=============================================#
# 
#    * @project_name : Nabesof-Md
#    * @author : Nabesof Tech 
#    * @youtube : https://youtube.com/@NRN300?si=G00_pFMNt5fiva48
#    * @description : Nabesof-Md ,A Multi-functional whatsapp bot md.
#    * @version 1.2.8
# 
# Don't change this [ /NabesofTechInfo/ ] name!
# Change from below link, else bot not works!

 

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https:https://github.com/nabesofmd/NABESOF-MD
WORKDIR /root/Nabesof/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
